trigger: none
pool: TodoAgent

parameters:
- name: deployBackend
  displayName: Deploy Backend (Python)
  type: boolean
  default: true

- name: deployFrontend
  displayName: Deploy Frontend (React)
  type: boolean
  default: true

stages:
  - stage: Scannigtool
    jobs:
      - job: ruffsacn
        displayName: RuffScan
        steps:
        - task: PowerShell@2
          displayName: Ruff Scanning Tool
          continueOnError: true
          inputs:
            targetType: 'inline'
            script: 'ruff check'

  - stage: publishArtifact
    jobs:
      - job: publishArtifact
        condition: eq(${{ parameters.deployBackend }}, true)
        displayName: Publish Artifact
        steps:
        - task: PublishPipelineArtifact@1
          displayName: Publish Artifact
          inputs:
            targetPath: '$(System.DefaultWorkingDirectory)'
            artifact: 'pyapp'
            publishLocation: 'pipeline'

  - stage: DeploytoVM
    jobs:
    - deployment: 
      environment:
       name: todo-ui-app
      #  resourceType: virtualMachine
       resourceName: backend-python-vm
      strategy: 
       runOnce:
         deploy:
           steps:
           - task: DownloadPipelineArtifact@2
             displayName: Download Artifact
             inputs:
               buildType: 'current'
               artifactName: 'pyapp'
               targetPath: '$(Pipeline.Workspace)pyapp'

           - task: Bash@3
             displayName: Copy Artifact to VM
             inputs:
               targetType: 'inline'
               script: 'cp -r $(Pipeline.Workspace)/pyapp /home/username/'

  - stage: build
    jobs: 
     - job: build
       steps:
       - task: NodeTool@0
         inputs:
           versionSource: 'spec'
           versionSpec: '16.x'
       - task: PowerShell@2
         inputs:
           targetType: 'inline'
           script: 'npm install'
       - task: PowerShell@2
         inputs:
           targetType: 'inline'
           script: 'npm run build'
       - task: PublishPipelineArtifact@1
         inputs:
           targetPath: '$(System.DefaultWorkingDirectory)/build'
           artifact: 'todouiapp'
           publishLocation: 'pipeline'
  - stage: deployment_to_vm
    jobs: 
    - deployment: deploytovm
      environment:
        name: app-env-deploy
        resourceType: VirtualMachine
      strategy:
       runOnce:
         deploy:
           steps:
           - task: DownloadPipelineArtifact@2
             inputs:
               buildType: 'specific'
               project: 'a0f1484e-6430-4e5a-a152-69063a459b63'
               definition: '52'
               buildVersionToDownload: 'specific'
               pipelineId: '668'
               artifactName: 'todouiapp'
               targetPath: '$(Pipeline.Workspace)'
           - task: Bash@3
             inputs:
                targetType: 'inline'
                script: 'sudo cp -r $(Pipeline.Workspace)/* /var/www/html'