trigger: none
pool: TodoAgent

parameters:
- name: deployBackend
  displayName: Deploy Backend (Python)
  type: boolean
  default: true

- name: deployFrontend
  displayName: Deploy Frontend (React)
  type: boolean
  default: true

stages:
  # 1. Scanning Stage
  - stage: Scannigtool
    jobs:
      - job: ruffsacn
        displayName: RuffScan
        steps:
        - task: PowerShell@2
          displayName: Ruff Scanning Tool
          continueOnError: true
          inputs:
            targetType: 'inline'
            # Backend folder mein ja kar scan karein
            script: |
              cd PyTodoBackendMonolith
              ruff check

  # 2. Backend Stage
  - stage: publishBackend
    dependsOn: Scannigtool
    condition: and(succeeded(), eq(${{ parameters.deployBackend }}, true))
    jobs:
      - job: publishArtifact
        steps:
        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: 'PyTodoBackendMonolith'
            artifact: 'pyapp'

  # 3. Backend Deployment
  - stage: DeployBackendtoVM
    dependsOn: publishBackend
    jobs:
    - deployment: deploy_backend
      environment: 
        name: todo-ui-app
        resourceName: backend-python-vm
      strategy: 
        runOnce:
          deploy:
            steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'pyapp'
                targetPath: '$(Pipeline.Workspace)/pyapp'
            - task: Bash@3
              inputs:
                targetType: 'inline'
                script: 'cp -r $(Pipeline.Workspace)/pyapp/* /home/username/app/'

  # 4. Frontend Build Stage
  - stage: buildFrontend
    dependsOn: Scannigtool
    condition: and(succeeded(), eq(${{ parameters.deployFrontend }}, true))
    jobs: 
     - job: build
       steps:
       - task: NodeTool@0
         inputs:
           versionSpec: '16.x'
       - task: Bash@3
         displayName: Build React App
         inputs:
           targetType: 'inline'
           # Folder ke andar ja kar install aur build karein
           workingDirectory: 'ReactTodoUIMonolith'
           script: |
             npm install
             npm run build
       - task: PublishPipelineArtifact@1
         inputs:
           targetPath: 'ReactTodoUIMonolith/build'
           artifact: 'todouiapp'

  # 5. Frontend Deployment
  - stage: DeployFrontendtoVM
    dependsOn: buildFrontend
    jobs: 
    - deployment: deploy_ui
      environment: 
        name: app-env-deploy
        resourceType: VirtualMachine
      strategy:
        runOnce:
          deploy:
            steps:
            - task: DownloadPipelineArtifact@2
              inputs:
                buildType: 'current'
                artifactName: 'todouiapp'
                targetPath: '$(Pipeline.Workspace)/ui'
            - task: Bash@3
              inputs:
                 targetType: 'inline'
                 script: 'sudo cp -r $(Pipeline.Workspace)/ui/* /var/www/html/'